const plaques = [
    { "id": "04", "text": "04" },
    { "id": "05", "text": "05" },
    { "id": "06", "text": "06" },
    { "id": "07", "text": "07" },
    { "id": "08", "text": "08" },
    { "id": "09", "text": "09" },
    { "id": "10", "text": "10" },
    { "id": "11", "text": "11" },
    { "id": "12", "text": "12" },
    { "id": "13", "text": "13" },
    { "id": "14", "text": "14" },
    { "id": "15", "text": "15" },
    { "id": "16", "text": "16" },
    { "id": "17", "text": "17" },
    { "id": "18", "text": "18" },
    { "id": "19", "text": "19" },
    { "id": "2A", "text": "2A" },
    { "id": "2B", "text": "2B" },
    { "id": "21", "text": "21" },
    { "id": "22", "text": "22" },
    { "id": "23", "text": "23" },
    { "id": "24", "text": "24" },
    { "id": "25", "text": "25" },
    { "id": "26", "text": "26" },
    { "id": "27", "text": "27" },
    { "id": "28", "text": "28" },
    { "id": "29", "text": "29" },
    { "id": "30", "text": "30" },
    { "id": "31", "text": "31" },
    { "id": "32", "text": "32" },
    { "id": "33", "text": "33" },
    { "id": "34", "text": "34" },
    { "id": "35", "text": "35" },
    { "id": "36", "text": "36" },
    { "id": "37", "text": "37" },
    { "id": "38", "text": "38" },
    { "id": "39", "text": "39" },
    { "id": "40", "text": "40" },
    { "id": "41", "text": "41" },
    { "id": "42", "text": "42" },
    { "id": "43", "text": "43" },
    { "id": "44", "text": "44" },
    { "id": "45", "text": "45" },
    { "id": "46", "text": "46" },
    { "id": "47", "text": "47" },
    { "id": "48", "text": "48" },
    { "id": "49", "text": "49" },
    { "id": "50", "text": "50" },
    { "id": "51", "text": "51" },
    { "id": "52", "text": "52" },
    { "id": "53", "text": "53" },
    { "id": "54", "text": "54" },
    { "id": "55", "text": "55" },
    { "id": "56", "text": "56" },
    { "id": "57", "text": "57" },
    { "id": "58", "text": "58" },
    { "id": "59", "text": "59" },
    { "id": "60", "text": "60" },
    { "id": "61", "text": "61" },
    { "id": "62", "text": "62" },
    { "id": "63", "text": "63" },
    { "id": "64", "text": "64" },
    { "id": "65", "text": "65" },
    { "id": "66", "text": "66" },
    { "id": "67", "text": "67" },
    { "id": "68", "text": "68" },
    { "id": "69", "text": "69" },
    { "id": "70", "text": "70" },
    { "id": "71", "text": "71" },
    { "id": "72", "text": "72" },
    { "id": "73", "text": "73" },
    { "id": "74", "text": "74" },
    { "id": "75", "text": "75" },
    { "id": "76", "text": "76" },
    { "id": "77", "text": "77" },
    { "id": "78", "text": "78" },
    { "id": "79", "text": "79" },
    { "id": "80", "text": "80" },
    { "id": "81", "text": "81" },
    { "id": "82", "text": "82" },
    { "id": "83", "text": "83" },
    { "id": "84", "text": "84" },
    { "id": "85", "text": "85" },
    { "id": "86", "text": "86" },
    { "id": "87", "text": "87" },
    { "id": "88", "text": "88" },
    { "id": "89", "text": "89" },
    { "id": "90", "text": "90" },
    { "id": "91", "text": "91" },
    { "id": "92", "text": "92" },
    { "id": "93", "text": "93" },
    { "id": "94", "text": "94" },
    { "id": "95", "text": "95" },
    { "id": "P", "text": "P" },
    { "id": "M", "text": "M" },
    { "id": "971", "text": "971" },
    { "id": "972", "text": "972" },
    { "id": "973", "text": "973" },
    { "id": "974", "text": "974" },
    { "id": "976", "text": "976" },
    { "id": "F", "text": "F" }
];
const postes = [
	{id: "Poste 1",text: "Poste 1 (RD27) Caen vers Deauville - Giratoire RD27 x RD40"},
	{id: "Poste 2",text: "Poste 2 (RD675) Caen vers Pont Audemer - Giratoire RD675 x RD228"},
	{id: "Poste 3",text: "Poste 3 (RD613) Caen vers Lisieux - Giratoire RD613 x RD41"},
	{id: "Poste 4",text: "Poste 4 (RD562) Le Hom vers Caen - Giratoire RD562 x RD257"},
	{id: "Poste 5",text: "Poste 5 (RD7) Caen vers DLD - Giratoire RD7 x RD404"},
	{id: "Poste 6",text: "Poste 6 (RD515) Caen vers Ouistreham - Giratoire RD514 x RD84"},
	{id: "Poste 7",text: "Poste 7 (A84) Caen vers Rennes - Aire de repos de St - Jean des Essartiens"},
	{id: "Poste 8",text: "Poste 8 (RN158) Caen vers Falaise - Aire de repos de Soulangy Ouest"},
];

const typeVehicule = [
    { "id": "1", "text": "VL" },
    { "id": "2", "text": "VL + caravane ou remorque" },
    { "id": "3", "text": "Camping-Car" },
    { "id": "4", "text": "Fourgonnettes et utilitaires transportant du matériel (artisan…)" },
    { "id": "5", "text": "Fourgonnettes et utilitaires transportant de la marchandise" },
    { "id": "6", "text": "PL porteur" },
    { "id": "7", "text": "PL articulé, semi-remorque" },
    { "id": "8", "text": "PL train routier (porteur + remorque)" }
]

export { plaques, postes, typeVehicule };
